### ISSUE TITLE
twitch -listuser causes exception on worker thread

### ISSUE THREAD

**Issue by KavenC** [KavenC/Linot#10]
2015-08-21|22:06:38|[DEBUG][linot.command_server.line.worker]: get cmd: ['twitch', '-listu']
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/home/pi/projects/Linot/linot/command_server.py", line 41, in _process_command
    args.proc(args, sender)
  File "/home/pi/projects/Linot/linot/arg_parser.py", line 99, in _process_args
    func(getattr(input_args, args), sender)
  File "/home/pi/projects/Linot/linot/services/twitch_notifier/service.py", line 232, in _list_users
    sender.send_message(msg.getvalue())
  File "/home/pi/projects/Linot/linot/command_submitter.py", line 11, in send_message
    return interface.send_message(self, msg)
  File "/home/pi/projects/Linot/linot/interfaces/line_interface.py", line 69, in send_message
    self._send_message_to_id(receiver.code, msg)
  File "/home/pi/projects/Linot/linot/interfaces/line_interface.py", line 84, in _send_message_to_id
    recvr.sendMessage(msg)
  File "/usr/local/lib/python2.7/dist-packages/line/models.py", line 68, in sendMessage
    raise e
Exception: Error: You need to login first. There is no valid certificate

**Comment by KavenC** [comment]
List user hit exception if there is no users at all. 

twitch notifier sends zero length string to the interface in this case. When the string goes to line_interface, it then triggers an exception in line package. 

The exception message is somewhat misdirecting. It is not a auth/ceritification problem, but the thrift implementation of line package that refuses zero length string.
